# R Programming — NPTEL Week 10
## String Substitution, Searching and Data Frames

Topics:
- `sub()` and `gsub()`
- `grep()` and `grepl()`
- Data frames
- `MASS::painters`
- `rownames()`, `colnames()`
- `is.numeric()` and `is.factor()`
- `summary()`
- `attach()` and `detach()`
- `subset()`
- `split()`
- `cbind()`, `merge()`, and `rbind()`

## 1. `sub()` and `gsub()`

`sub()` replaces the **first** matching occurrence. `gsub()` replaces **all** matching occurrences.

In [1]:
y = "Number of participants: 25"

sub("25", "30", y)

[1] "Number of participants: 30"

In [2]:
y = "Mr. Singh is the smart one. Mr. Singh is funny, too."

# Replace only the first occurrence
sub("Mr. Singh", "Professor Jha", y)

# Replace every occurrence
gsub("Mr. Singh", "Professor Jha", y)

[1] "Professor Jha is the smart one. Mr. Singh is funny, too."

[1] "Professor Jha is the smart one. Professor Jha is funny, too."

## 2. `grep()`

`grep()` searches a character vector and returns the indices of elements containing the pattern. With `value = TRUE`, it returns the matching strings.

In [3]:
str = c(
  "R Course",
  "exercises",
  "include examples of R language"
)

grep("ex", str, value = TRUE)
grep("ex", str, value = FALSE)

[1] "exercises"                      "include examples of R language"

[1] 2 3

### `ignore.case` in `grep()`

In [4]:
str = c(
  "R Course",
  "exercises",
  "include examples of r language",
  "in R software."
)

grep("R", str, ignore.case = FALSE, value = TRUE)
grep("R", str, ignore.case = TRUE, value = TRUE)
grep("R", str, ignore.case = TRUE, value = FALSE)
grep("R", str, ignore.case = FALSE, value = FALSE)

[1] "R Course"       "in R software."

[1] "R Course"                       "exercises"
[3] "include examples of r language" "in R software."

[1] 1 2 3 4

[1] 1 4

### More `grep()` examples

In [5]:
x = "R course 24.07.2022"
y = "Number of participants: 25"

c(x, y)

grep("our", c(x, y))
grep("Num", c(x, y))

[1] "R course 24.07.2022"        "Number of participants: 25"

[1] 1

[1] 2

## 3. `grepl()`

`grepl()` returns `TRUE` or `FALSE` for each element, indicating whether the pattern occurs.

In [6]:
str = c(
  "R Course",
  "exercises",
  "include examples of R language"
)

grepl("R", str)
grepl("ex", str)

[1]  TRUE FALSE  TRUE

[1] FALSE  TRUE  TRUE

## 4. Data Frames

A data frame stores variables of equal length as columns and observations as rows. Unlike a matrix, a data frame can contain different types of variables.

In [7]:
students = data.frame(
  Name = c("Asha", "Riya", "Neha", "Pooja"),
  Marks = c(85, 92, 78, 88),
  Branch = c("CMPN", "IT", "CMPN", "AI")
)

students

  Name  Marks Branch
1 Asha  85    CMPN
2 Riya  92    IT
3 Neha  78    CMPN
4 Pooja 88    AI

### Accessing columns

In [8]:
students$Name
students$Marks
students$Branch

[1] "Asha"  "Riya"  "Neha"  "Pooja"

[1] 85 92 78 88

[1] "CMPN" "IT"   "CMPN" "AI"

## 5. The `painters` data frame from MASS

The NPTEL notes use the `painters` data frame from the `MASS` package.

In [9]:
library(MASS)
painters

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A
F. Zucarro      10          13       8      8         B
Fr. Salviata    13          15       8      8         B
Parmigiano      10          15       6      6         B
Primaticcio     15          14       7     10         B
T. Zucarro      13          14      10      9         B
Volterra        12          15       5      8         B
Barocci         14          15       6     10         C
Cortona         16          14      12      6         C
Josepin         10          10       6      2         C
L. Jordaens     13          12       9      6         C
Testa           11          15       0      6         C
Vanius          15          15      12     13         C
Bassano          6           8      17      0         D
Bellini          4           6      14      0         D
Giorgione        8           9      18      4         D
Murillo          6           8      15      4         D
Palma Giovane   12           9      14      6         D
Palma Vecchio    5           6      16      0         D
Pordenone        8          14      17      5         D
Tintoretto      15          14      16      4         D
Titian          12          15      18      6         D
Veronese        15          10      16      3         D
Albani          14          14      10      6         E
Caravaggio       6           6      16      0         E
Corregio        13          13      15     12         E
Domenichino     15          17       9     17         E
Guercino        18          10      10      4         E
Lanfranco       14          13      10      5         E
The Carraci     15          17      13     13         E
Durer            8          10      10      8         F
Holbein          9          10      16     13         F
Pourbus          4          15       6      6         F
Van Leyden       8           6       6      4         F
Diepenbeck      11          10      14      6         G
J. Jordaens     10           8      16      6         G
Otho Venius     13          14      10     10         G
Rembrandt       15           6      17     12         G
Rubens          18          13      17     17         G
Teniers         15          12      13      6         G
Van Dyck        15          10      17     13         G
Bourdon         10           8       8      4         H
Le Brun         16          16       8     16         H
Le Suer         15          15       4     15         H
Poussin         15          17       6     15         H

### Row names

In [10]:
rownames(painters)

 [1] "Da Udine"        "Da Vinci"        "Del Piombo"      "Del Sarto"
 [5] "Fr. Penni"       "Guilio Romano"   "Michelangelo"    "Perino del Vaga"
 [9] "Perugino"        "Raphael"         "F. Zucarro"      "Fr. Salviata"
[13] "Parmigiano"      "Primaticcio"     "T. Zucarro"      "Volterra"
[17] "Barocci"         "Cortona"         "Josepin"         "L. Jordaens"
[21] "Testa"           "Vanius"          "Bassano"         "Bellini"
[25] "Giorgione"       "Murillo"         "Palma Giovane"   "Palma Vecchio"
[29] "Pordenone"       "Tintoretto"      "Titian"          "Veronese"
[33] "Albani"          "Caravaggio"      "Corregio"        "Domenichino"
[37] "Guercino"        "Lanfranco"       "The Carraci"     "Durer"
[41] "Holbein"         "Pourbus"         "Van Leyden"      "Diepenbeck"
[45] "J. Jordaens"     "Otho Venius"     "Rembrandt"       "Rubens"
[49] "Teniers"         "Van Dyck"        "Bourdon"         "Le Brun"
[53] "Le Suer"         "Poussin"

### Column names

In [11]:
colnames(painters)

[1] "Composition" "Drawing"     "Colour"      "Expression"  "School"

### Checking variable types

In [12]:
is.numeric(painters$Drawing)
is.numeric(painters$School)

is.factor(painters$School)
is.factor(painters$Drawing)

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

## 6. `summary()`

In [13]:
summary(painters)

  Composition       Drawing          Colour        Expression         School
 Min.   : 0.00   Min.   : 6.00   Min.   : 0.00   Min.   : 0.000   A      :10
 1st Qu.: 8.25   1st Qu.:10.00   1st Qu.: 7.25   1st Qu.: 4.000   D      :10
 Median :12.50   Median :13.50   Median :10.00   Median : 6.000   E      : 7
 Mean   :11.56   Mean   :12.46   Mean   :10.94   Mean   : 7.667   G      : 7
 3rd Qu.:15.00   3rd Qu.:15.00   3rd Qu.:16.00   3rd Qu.:11.500   B      : 6
 Max.   :18.00   Max.   :18.00   Max.   :18.00   Max.   :18.000   C      : 6
                                                                  (Other): 8

In [14]:
summary(painters$School)
summary(painters$Composition)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

## 7. `attach()` and `detach()`

In [15]:
attach(painters)

summary(School)
summary(Composition)

detach(painters)

 A  B  C  D  E  F  G  H
10  6  6 10  7  4  7  4

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   0.00    8.25   12.50   11.56   15.00   18.00

## 8. `subset()`

In [16]:
subset(painters, School == "F")

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

In [17]:
subset(painters, Composition <= 6)

              Composition Drawing Colour Expression School
Fr. Penni     0           15       8     0          A
Perugino      4           12      10     4          A
Bassano       6            8      17     0          D
Bellini       4            6      14     0          D
Murillo       6            8      15     4          D
Palma Vecchio 5            6      16     0          D
Caravaggio    6            6      16     0          E
Pourbus       4           15       6     6          F

### Selecting specific columns with `subset()`

In [18]:
subset(
  painters,
  School == "F",
  select = c(-3, -5)
)

           Composition Drawing Expression
Durer      8           10       8
Holbein    9           10      13
Pourbus    4           15       6
Van Leyden 8            6       4

### Equivalent row selection using indexing

In [19]:
painters[painters[["School"]] == "F", ]

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

## 9. `split()`

In [20]:
splitted = split(painters, painters$School)

splitted

$A
                Composition Drawing Colour Expression School
Da Udine                 10       8     16          3      A
Da Vinci                 15      16      4         14      A
Del Piombo                8      13     16          7      A
Del Sarto                12      16      9          8      A
Fr. Penni                 0      15      8          0      A
Guilio Romano            15      16      4         14      A
Michelangelo              8      17      4          8      A
Perino del Vaga          15      16      7          6      A
Perugino                  4      12     10          4      A
Raphael                  17      18     12         18      A

$B
             Composition Drawing Colour Expression School
F. Zucarro            10      13      8          8      B
Fr. Salviata          13      15      8          8      B
Parmigiano            10      15      6          6      B
Primaticcio           15      14      7         10      B
T. Zucarro            13      14     10          9      B
Volterra              12      15      5          8      B

$C
            Composition Drawing Colour Expression School
Barocci              14      15      6         10      C
Cortona              16      14     12          6      C
Josepin              10      10      6          2      C
L. Jordaens          13      12      9          6      C
Testa                11      15      0          6      C
Vanius               15      15     12         13      C

$D
              Composition Drawing Colour Expression School
Bassano                 6       8     17          0      D
Bellini                 4       6     14          0      D
Giorgione               8       9     18          4      D
Murillo                 6       8     15          4      D
Palma Giovane          12       9     14          6      D
Palma Vecchio           5       6     16          0      D
Pordenone               8      14     17          5      D
Tintoretto             15      14     16          4      D
Titian                 12      15     18          6      D
Veronese               15      10     16          3      D

$E
            Composition Drawing Colour Expression School
Albani               14      14     10          6      E
Caravaggio            6       6     16          0      E
Corregio             13      13     15         12      E
Domenichino          15      17      9         17      E
Guercino             18      10     10          4      E
Lanfranco            14      13     10          5      E
The Carraci          15      17     13         13      E

$F
           Composition Drawing Colour Expression School
Durer                8      10     10          8      F
Holbein              9      10     16         13      F
Pourbus              4      15      6          6      F
Van Leyden           8       6      6          4      F

$G
            Composition Drawing Colour Expression School
Diepenbeck           11      10     14          6      G
J. Jordaens          10       8     16          6      G
Otho Venius          13      14     10         10      G
Rembrandt            15       6     17         12      G
Rubens               18      13     17         17      G
Teniers              15      12     13          6      G
Van Dyck             15      10     17         13      G

$H
        Composition Drawing Colour Expression School
Bourdon          10       8      8          4      H
Le Brun          16      16      8         16      H
Le Suer          15      15      4         15      H
Poussin          15      17      6         15      H

### Individual groups

In [21]:
splitted$A
splitted$F
splitted$H

                Composition Drawing Colour Expression School
Da Udine        10           8      16      3         A
Da Vinci        15          16       4     14         A
Del Piombo       8          13      16      7         A
Del Sarto       12          16       9      8         A
Fr. Penni        0          15       8      0         A
Guilio Romano   15          16       4     14         A
Michelangelo     8          17       4      8         A
Perino del Vaga 15          16       7      6         A
Perugino         4          12      10      4         A
Raphael         17          18      12     18         A

           Composition Drawing Colour Expression School
Durer      8           10      10      8         F
Holbein    9           10      16     13         F
Pourbus    4           15       6      6         F
Van Leyden 8            6       6      4         F

        Composition Drawing Colour Expression School
Bourdon 10           8      8       4         H
Le Brun 16          16      8      16         H
Le Suer 15          15      4      15         H
Poussin 15          17      6      15         H

### Check whether a split object is a data frame

In [22]:
is.data.frame(splitted$A)

[1] TRUE

## 10. Combining Data Frames

The notes introduce three main operations:

- `cbind()` — combine columns side-by-side
- `merge()` — join using a common column
- `rbind()` — stack rows vertically

In [23]:
df1 = data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)

df2 = data.frame(
  state = c("UP", "MP", "AP", "JK"),
  samplesize = c(100, 200, 300, 400),
  surveycompleted = c("Yes", "No", "Yes", "No")
)

df1
df2

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

  state samplesize surveycompleted
1 UP    100        Yes
2 MP    200        No
3 AP    300        Yes
4 JK    400        No

## 11. `cbind()` — horizontal combination

In [24]:
cbind(df1, df2)

  state popnsize state samplesize surveycompleted
1 UP    1000     UP    100        Yes
2 MP    2000     MP    200        No
3 AP    3000     AP    300        Yes
4 JK    4000     JK    400        No

## 12. `merge()` — combine using a common column

Both data frames have `state` in common, so we merge using `by = "state"`.

In [25]:
merge(df1, df2, by = "state")

  state popnsize samplesize surveycompleted
1 AP    3000     300        Yes
2 JK    4000     400        No
3 MP    2000     200        No
4 UP    1000     100        Yes

## 13. `rbind()` — vertical combination

In [26]:
df11 = data.frame(
  state = c("UP", "MP", "AP", "JK"),
  popnsize = c(1000, 2000, 3000, 4000)
)

df22 = data.frame(
  state = c("Bihar", "Delhi", "Punjab"),
  popnsize = c(100, 200, 300)
)

df11
df22

  state popnsize
1 UP    1000
2 MP    2000
3 AP    3000
4 JK    4000

  state  popnsize
1 Bihar  100
2 Delhi  200
3 Punjab 300

In [27]:
rbind(df11, df22)

  state  popnsize
1 UP     1000
2 MP     2000
3 AP     3000
4 JK     4000
5 Bihar   100
6 Delhi   200
7 Punjab  300

## 14. Practice Questions

1. Replace the first `"R"` in a string using `sub()`.
2. Replace every `"R"` using `gsub()`.
3. Use `grep()` to find strings containing `"data"`.
4. Use `grepl()` to return TRUE/FALSE for the same search.
5. Create a data frame containing Student, Marks and Branch.
6. Select students with Marks greater than 80 using `subset()`.
7. Split a data frame according to Branch.
8. Create two data frames and combine them with `cbind()`.
9. Merge two data frames using a common ID column.
10. Stack two compatible data frames using `rbind()`.

In [28]:
# Practice 1
s = "R is useful. R is popular."
sub("R", "Python", s)

# Practice 2
gsub("R", "Python", s)

# Practice 3
words = c("data science", "machine learning", "data frame", "statistics")
grep("data", words, value = TRUE)

# Practice 4
grepl("data", words)

# Practice 5
student_df = data.frame(
  Student = c("A", "B", "C", "D"),
  Marks = c(75, 91, 84, 68),
  Branch = c("CMPN", "IT", "CMPN", "AI")
)
student_df

# Practice 6
subset(student_df, Marks > 80)

# Practice 7
split(student_df, student_df$Branch)

# Practice 8
extra = data.frame(Attendance = c(90, 95, 88, 80))
cbind(student_df, extra)

# Practice 9
id1 = data.frame(ID = c(1,2,3), Name = c("A","B","C"))
id2 = data.frame(ID = c(1,2,3), Score = c(80,90,85))
merge(id1, id2, by = "ID")

# Practice 10
rbind(
  data.frame(ID = c(4,5), Name = c("D","E")),
  data.frame(ID = c(6,7), Name = c("F","G"))
)

[1] "Python is useful. R is popular."

[1] "Python is useful. Python is popular."

[1] "data science" "data frame"

[1]  TRUE FALSE  TRUE FALSE

  Student Marks Branch
1 A       75    CMPN
2 B       91    IT
3 C       84    CMPN
4 D       68    AI

  Student Marks Branch
2 B       91    IT
3 C       84    CMPN

$AI
  Student Marks Branch
4       D    68     AI

$CMPN
  Student Marks Branch
1       A    75   CMPN
3       C    84   CMPN

$IT
  Student Marks Branch
2       B    91     IT

  Student Marks Branch Attendance
1 A       75    CMPN   90
2 B       91    IT     95
3 C       84    CMPN   88
4 D       68    AI     80

  ID Name Score
1 1  A    80
2 2  B    90
3 3  C    85

  ID Name
1 4  D
2 5  E
3 6  F
4 7  G


| Function | Purpose |
|---|---|
| `sub()` | Replace first match |
| `gsub()` | Replace all matches |
| `grep()` | Find matching elements/positions |
| `grepl()` | Return TRUE/FALSE for matches |
| `data.frame()` | Create a data frame |
| `rownames()` | Get/set row names |
| `colnames()` | Get/set column names |
| `is.numeric()` | Check whether an object is numeric |
| `is.factor()` | Check whether an object is a factor |
| `summary()` | Quick summary of data |
| `attach()` | Refer to data-frame columns directly |
| `detach()` | Remove an attached data frame |
| `subset()` | Select rows/columns satisfying conditions |
| `split()` | Partition data by a variable |
| `cbind()` | Combine columns horizontally |
| `merge()` | Join data frames using common columns |
| `rbind()` | Stack rows vertically |