# R Programming - Week 3
## Basics of Calculations, Built-in Functions and Matrices
*Jyotsna Kasibhotla - 23102B0078*

This notebook demonstrates:
1. Calculations with data vectors
2. Power operations
3. Integer and modulo division
4. Built-in functions
5. Assignment of variables
6. Matrix creation and manipulation
7. Matrix properties

*Basic Arithmetic with Vectors - Addition, Subtraction, Multiplication , Division*

In [1]:
# Addition of two vectors
c(2, 3, 5, 7) + c(-2, -3, -5, 8)
# Subtraction of two vectors
c(2, 3, 5, 7) - c(1, 1, 2, 3)
# Multiplication of two vectors
c(2, 3, 5, 7) * c(1, 2, 3, 4)
# Division of two vectors
c(2, 3, 5, 7) / c(1, 2, 5, 7)

[1]  0  0  0 15

[1] 1 2 3 4

[1]  2  6 15 28

[1] 2.0 1.5 1.0 1.0

*Creating and Displaying a Vector*

In [2]:
x <- c(2, 3, 5, 7)

x
mode(x)

[1] 2 3 5 7

[1] "numeric"

*Power Operation*

In [4]:
2^3
2**3
2^0.5

[1] 8

[1] 8

[1] 1.414214

*Power Operation on a Vector*

In [5]:
c(2, 3, 5, 7)^2

[1]  4  9 25 49

*Vector Raised to Another Vector*

In [6]:
c(2, 3, 5, 7)^c(2, 3)

[1]   4  27  25 343

*Vector Recycling Example*

In [7]:
c(1, 2, 3, 4, 5, 6)^c(2, 3, 4)

[1]    1    8   81   16  125 1296

*Recycling Warning*

In [8]:
c(2, 3, 5, 7)^c(2, 3, 4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
"longer object length is not a multiple of shorter object length"

[1]   4  27 625  49

*Integer Division*

In [9]:
2 %/% 2
5 %/% 2
7 %/% 3

[1] 1

[1] 2

[1] 2

*Integer Division with Vector*

In [10]:
c(2, 3, 5, 7) %/% 2

[1] 1 1 2 3

*Integer Division with Two Vectors*

In [11]:
c(2, 3, 5, 7) %/% c(2, 3)

[1] 1 1 2 2

*Integer Division Warning*

In [12]:
c(2, 3, 5) %/% c(2, 3)

Warning message in c(2, 3, 5)%/%c(2, 3):
"longer object length is not a multiple of shorter object length"

[1] 1 1 2

*Modulo Division*

In [13]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

*Modulo with Vector*

In [14]:
c(2, 3, 5, 7) %% 2

[1] 0 1 1 1

*Modulo with Two Vectors*

In [15]:
c(2, 3, 5, 7) %% c(2, 3)

[1] 0 0 1 1

*Modulo with Unequal Lengths*

In [16]:
c(2, 3, 5) %% c(2, 3)

Warning message in c(2, 3, 5)%%c(2, 3):
"longer object length is not a multiple of shorter object length"

[1] 0 0 1

## Built-in Functions

*Maximum*

In [17]:
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))

[1] 3.4

[1] 3.4

*Minimum*

In [18]:
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] -7.8

[1] -7.8

*Mean*

In [19]:
mean(c(2, 3, 4))

[1] 3

*Absolute Value*

In [20]:
abs(-4)
abs(c(-1, -2, -3, 4, 5))

[1] 4

[1] 1 2 3 4 5

*Square Root*

In [21]:
sqrt(4)
sqrt(c(4, 9, 16, 25))

[1] 2

[1] 2 3 4 5

*Sum and Product*

In [22]:
sum(c(2, 3, 5, 7))

[1] 17

In [23]:
prod(c(2, 3, 5, 7))

[1] 210

*Rounding Functions*

round

In [24]:
round(1.23)
round(1.83)

[1] 1

[1] 2

floor

In [25]:
floor(1.83)

[1] 1

ceiling

In [26]:
ceiling(1.23)

[1] 2

*Logarithms*

In [27]:
log(10)
log(exp(1))
log(c(10, 100, 1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

*Log Base 10*

In [28]:
log10(10)
log10(100)
log10(c(10, 100, 1000))

[1] 1

[1] 2

[1] 1 2 3

*other built-in functions*

In [29]:
# Exponential
exp(1)

# Base-2 logarithm
log2(8)

# Trigonometric functions
sin(pi / 2)
cos(0)
tan(pi / 4)

# Inverse trigonometric functions
asin(1)
acos(1)
atan(1)

[1] 2.718282

[1] 3

[1] 1

[1] 1

[1] 1

[1] 1.570796

[1] 0

[1] 0.7853982

## Matrices

*Create a matrix*

In [30]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = c(1, 2, 3, 4, 5, 6, 7, 8)
)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

*Access a Matrix Element*

In [33]:
x[3, 2]
x[2, 1]
x[4, 2]

[1] 7

[1] 2

[1] 8

*Create Matrix Column-Wise Explicitly*

In [34]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = c(1, 2, 3, 4, 5, 6, 7, 8),
  byrow = FALSE
)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

*Create Matrix Row-Wise*

In [35]:
y <- matrix(
  nrow = 4,
  ncol = 2,
  data = c(1, 2, 3, 4, 5, 6, 7, 8),
  byrow = TRUE
)

y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

*Matrix Dimensions*

In [36]:
dim(x)

[1] 4 2

*Number of Rows*

In [37]:
nrow(x)

[1] 4

*Number of Columns*

In [38]:
ncol(x)

[1] 2

*Matrix Mode*

In [39]:
mode(x)

[1] "numeric"

*Matrix Attributes*

In [40]:
attributes(x)

$dim
[1] 4 2

*Check Whether Object Is a Matrix*

In [41]:
is.matrix(x)

[1] TRUE

In [42]:
v <- c(1, 2, 3, 4)

is.matrix(v)

[1] FALSE

*Convert Vector to Matrix*

In [43]:
v <- c(1, 2, 3, 4)

m <- as.matrix(v)

m

     [,1]
[1,] 1
[2,] 2
[3,] 3
[4,] 4

In [44]:
is.matrix(m)

[1] TRUE

*Matrix Calculations*

In [45]:
x + x
x * 2
x^2
sum(x)
max(x)
min(x)
mean(x)

     [,1] [,2]
[1,] 2    10
[2,] 4    12
[3,] 6    14
[4,] 8    16

     [,1] [,2]
[1,] 2    10
[2,] 4    12
[3,] 6    14
[4,] 8    16

     [,1] [,2]
[1,]  1   25
[2,]  4   36
[3,]  9   49
[4,] 16   64

[1] 36

[1] 8

[1] 1

[1] 4.5

*Complete Matrix Example*

In [46]:
# Create a 3 x 2 matrix
marks <- matrix(
  c(80, 75,
    90, 85,
    70, 95),
  nrow = 3,
  ncol = 2,
  byrow = TRUE
)

# Display matrix
marks

# Access an element
marks[2, 2]

# Matrix properties
dim(marks)
nrow(marks)
ncol(marks)
mode(marks)
attributes(marks)

# Mathematical operations
marks^2
marks * 2

# Statistical functions
sum(marks)
mean(marks)
max(marks)
min(marks)

# Check whether it is a matrix
is.matrix(marks)

     [,1] [,2]
[1,] 80   75
[2,] 90   85
[3,] 70   95

[1] 85

[1] 3 2

[1] 3

[1] 2

[1] "numeric"

$dim
[1] 3 2

     [,1] [,2]
[1,] 6400 5625
[2,] 8100 7225
[3,] 4900 9025

     [,1] [,2]
[1,] 160  150
[2,] 180  170
[3,] 140  190

[1] 495

[1] 82.5

[1] 95

[1] 70

[1] TRUE

*final demonstration*

In [47]:
# Create vectors
a <- c(2, 3, 5, 7)
b <- c(1, 2, 3, 4)

# Arithmetic operations
addition <- a + b
subtraction <- a - b
multiplication <- a * b
division <- a / b

# Power
power <- a^2

# Integer division
integer_division <- a %/% 2

# Modulo
remainder <- a %% 2

# Built-in functions
maximum <- max(a)
minimum <- min(a)
average <- mean(a)
total <- sum(a)
product <- prod(a)

# Display results
addition
subtraction
multiplication
division
power
integer_division
remainder

maximum
minimum
average
total
product

[1]  3  5  8 11

[1] 1 1 2 3

[1]  2  6 15 28

[1] 2.000000 1.500000 1.666667 1.750000

[1]  4  9 25 49

[1] 1 1 2 3

[1] 0 1 1 1

[1] 7

[1] 2

[1] 4.25

[1] 17

[1] 210

*matrix final example*

In [48]:
# Create a 4 x 2 matrix
M <- matrix(
  c(1, 2, 3, 4, 5, 6, 7, 8),
  nrow = 4,
  ncol = 2,
  byrow = TRUE
)

# Display matrix
M

# Access an element
M[3, 2]

# Matrix properties
dim(M)
nrow(M)
ncol(M)
mode(M)
attributes(M)

# Mathematical operations
M^2
M * 2

# Statistical functions
sum(M)
mean(M)
max(M)
min(M)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

[1] 6

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

     [,1] [,2]
[1,]  1    4
[2,]  9   16
[3,] 25   36
[4,] 49   64

     [,1] [,2]
[1,]  2    4
[2,]  6    8
[3,] 10   12
[4,] 14   16

[1] 36

[1] 4.5

[1] 8

[1] 1

## Conclusion

In this experiment, the basic features of R programming were implemented.
Arithmetic operations were performed on scalar values and data vectors.
Power operations, integer division and modulo division were studied along
with R's vector recycling behaviour.

Several built-in functions such as max(), min(), mean(), abs(), sqrt(),
sum(), prod(), round(), log() and log10() were implemented.

Matrix creation and manipulation were also studied. Matrices were created
using matrix(), elements were accessed using row and column indices, and
matrix properties were obtained using dim(), nrow(), ncol(), mode() and
attributes().

Thus, the experiment provided a basic understanding of calculations,
built-in functions, assignments and matrices in R programming.