# R Programming – NPTEL Week 7 Practical Notebook

**Topics covered from the provided NPTEL Week 7 notes:**
1. Sequences
2. Sequences of dates
3. Sequences of alphabets
4. Repeats using `rep()`
5. Sorting using `sort()`
6. Ordering using `order()`
7. Mode using `mode()`
8. Lists and list indexing

## 1. Sequences

The notes introduce `seq()` for generating regular sequences. The `:` operator can also generate sequences with a unit increment/decrement.

In [1]:
# Continuous sequences with unit increment
1:10
10:1
5:15
15:5

# Negative sequences
-1:-10
-10:-1
-5:-15
-15:-5

# Decimal sequences using :
1.23:10
1.23:10.54
10.54:2.23
-1.23:-10
-5.23:6

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

### Using `seq()`

In [3]:
# Basic seq()
seq(10)
seq(1:10)

# Sequence with a predefined variable and constant increment
x <- 2
seq(1, x, x/10)

x <- 50
seq(0, x, x/10)

# Store a sequence and perform an operation
x <- seq(1, 50, 1/2)
x

y <- 2 * x
y

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

[1] 1.0 1.2 1.4 1.6 1.8 2.0

 [1]  0  5 10 15 20 25 30 35 40 45 50

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

### Index vector

In [4]:
x <- c(9, 8, 7, 6)
ind <- seq(along = x)

ind
x[ind[2]]

[1] 1 2 3 4

[1] 8

## 2. Date Sequences

The notes use `as.Date()` together with `seq()` to generate sequences by days, months and years. `Sys.time()` gives the current date and time, while `Sys.Date()` gives the current date.

In [5]:
# Current date and time
Sys.time()

# Current date
Sys.Date()

# Sequence of first day of years
seq(
  as.Date("2010-01-01"),
  as.Date("2017-01-01"),
  by = "years"
)

# Sequence of days
seq(
  as.Date("2017-01-01"),
  by = "days",
  length.out = 6
)

# Sequence of months
seq(
  as.Date("2017-01-01"),
  by = "months",
  length.out = 6
)

# Sequence of years
seq(
  as.Date("2017-01-01"),
  by = "years",
  length.out = 6
)

[1] "2026-09-01 08:41:48 UTC"

[1] "2026-09-01"

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

### Date sequence with a defined start and end date

In [6]:
startdate <- as.Date("2016-01-01")
enddate <- as.Date("2017-01-01")

out <- seq(enddate, startdate, by = "-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

## 3. Alphabet Sequences

The notes use:
- `letters` for lowercase alphabets
- `LETTERS` for uppercase alphabets

In [7]:
# Lowercase alphabets
letters

letters[1:3]
letters[3:1]
letters[21:23]
letters[2]

# Uppercase alphabets
LETTERS

LETTERS[1:3]
LETTERS[3:1]
LETTERS[21:23]
LETTERS[2]

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

[1] "a" "b" "c"

[1] "c" "b" "a"

[1] "u" "v" "w"

[1] "b"

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

[1] "A" "B" "C"

[1] "C" "B" "A"

[1] "U" "V" "W"

[1] "B"

## 4. Repeats using `rep()`

The `rep()` function replicates numeric values, character values, or vector elements.

Main forms:
- `rep(x, times = n)` → repeats the complete object
- `rep(x, each = n)` → repeats each element
- `rep(x, length.out = n)` / `rep(x, length = n)` → produces a specified length

In [8]:
# Repeat a value
rep(3.5, times = 10)

# Repeat a complete vector
rep(1:4, times = 2)

# Repeat every element
x <- 1:4
rep(x, times = 3)
rep(x, each = 3)

# each and times together
rep(1:4, each = 2)
rep(1:4, each = 2, times = 3)
rep(1:4, times = 3, each = 2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

### Different number of repetitions for each element

In [9]:
# Elements 1, 2, 3 and 4 are repeated 2, 3, 4 and 5 times
rep(1:4, 2:5)

# Generate the repetition counts using seq()
ans <- seq(from = 2, to = 8, by = 2)
ans

rep(1:4, ans)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

[1] 2 4 6 8

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

### Repeating matrices and character values

In [10]:
# Matrix repetition
x <- matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE)
x
rep(x, 3)

# Character repetition
rep(c("a", "b", "c"), 2)
rep(c("apple", "banana", "cake"), 2)

# Pre-specified output length
rep(2, length.out = 5)
rep(2, length = 5)
rep(c(2, 3), length = 5)
rep(c(2, 3, 4), length = 5)

rep("apple", length = 5)
rep(c("a", "b", "c"), length = 2)
rep(c("a", "b", "c"), length = 5)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

[1] 2 2 2 2 2

[1] 2 2 2 2 2

[1] 2 3 2 3 2

[1] 2 3 4 2 3

[1] "apple" "apple" "apple" "apple" "apple"

[1] "a" "b"

[1] "a" "b" "c" "a" "b"

## 5. Sorting

`sort()` sorts a vector in ascending order by default. Set `decreasing = TRUE` for descending order.

In [11]:
y <- c(8, 5, 7, 6)

y
sort(y)
sort(y, decreasing = TRUE)

# Sorting with missing values
z <- c(8, NA, 5, 7, 6)

sort(z, na.last = TRUE)   # NA last
sort(z, na.last = FALSE)  # NA first
sort(z, na.last = NA)     # remove NA

[1] 8 5 7 6

[1] 5 6 7 8

[1] 8 7 6 5

[1]  5  6  7  8 NA

[1] NA  5  6  7  8

[1] 5 6 7 8

## 6. Ordering

`order()` returns the **positions/indices** that would arrange a vector in sorted order.

For `y = c(9, 8, 5, 7, 6)`, the ascending order of values is `5, 6, 7, 8, 9`, whose original positions are `3, 5, 4, 2, 1`.

In [12]:
y <- c(9, 8, 5, 7, 6)

y
order(y)
order(y, decreasing = TRUE)

# Use order() to actually rearrange the vector
y[order(y)]
y[order(y, decreasing = TRUE)]

[1] 9 8 5 7 6

[1] 3 5 4 2 1

[1] 1 2 4 5 3

[1] 5 6 7 8 9

[1] 9 8 7 6 5

## 7. Mode

The `mode()` function indicates how an R object is stored. The notes demonstrate numeric, character, list and function modes.

In [13]:
mode(2.432)
mode(c(3, 4, 5, 6, 7, 8))
mode("India")
mode(c("India", "CANADA"))

mode(factor(c("UP", "MP")))
mode(list("India", "USA"))

df <- data.frame(
  x = 1:2,
  y = c("India", "USA")
)
mode(df)

mode(print)

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

[1] "numeric"

[1] "list"

[1] "list"

[1] "function"

## 8. Lists

Unlike vectors, lists can contain objects of different types. The notes demonstrate lists containing character vectors, numeric vectors and matrices. Lists can also contain other structured objects.

In [14]:
# A list with different object types
z1 <- list(
  c("water", "juice", "lemonade"),
  rep(1:4, each = 2),
  matrix(data = 5:8, nrow = 2, ncol = 2, byrow = TRUE)
)

z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### Accessing list elements with `[[ ]]`

In [15]:
# First element of the list
z1[[1]]

# Extract "juice"
z1[[1]][2]

# Compare [ ] and [[ ]]
z1[1]
z1[[1]]

# The notes specifically demonstrate that:
# z1[1][2] does NOT extract "juice"
z1[1][2]

# Correct extraction:
z1[[1]][2]

[1] "water"    "juice"    "lemonade"

[1] "juice"

[[1]]
[1] "water"    "juice"    "lemonade"

[1] "water"    "juice"    "lemonade"

[[1]]
NULL

[1] "juice"

### Lists containing matrices

In [16]:
x1 <- matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE)
x2 <- matrix(nrow = 2, ncol = 2, data = 5:8, byrow = TRUE)

x1
x2
x1 + x2

# Store matrices in a list
matlist <- list(x1, x2)
matlist

matlist[1]
matlist[2]

# Extract the matrix itself
matlist[[1]]
matlist[[2]]

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

### Named list elements

In [17]:
student_data <- list(
  Students = c("Asha", "Ravi", "Meena"),
  Marks = c(85, 92, 78),
  Passed = c(TRUE, TRUE, TRUE)
)

student_data

# Access by name
student_data[["Students"]]
student_data$Students

# Access by position
student_data[[2]]

# Extract a sublist
student_data[c(1, 3)]

$Students
[1] "Asha"  "Ravi"  "Meena"

$Marks
[1] 85 92 78

$Passed
[1] TRUE TRUE TRUE

[1] "Asha"  "Ravi"  "Meena"

[1] "Asha"  "Ravi"  "Meena"

[1] 85 92 78

$Students
[1] "Asha"  "Ravi"  "Meena"

$Passed
[1] TRUE TRUE TRUE

## 9. Mini Practical Exercise

Run the following cells to verify that you can reproduce the main operations from the notes.

In [18]:
# Exercise 1: sequence from 5 to 25 with increment 2
seq(5, 25, by = 2)

# Exercise 2: six monthly dates starting from 2026-01-01
seq(as.Date("2026-01-01"), by = "months", length.out = 6)

# Exercise 3: uppercase letters from M to R
LETTERS[13:18]

# Exercise 4: repeat 1:4, each element 3 times
rep(1:4, each = 3)

# Exercise 5: sort descending
values <- c(18, 5, 12, 3, 20, 9)
sort(values, decreasing = TRUE)

# Exercise 6: find ordering positions
order(values)

# Exercise 7: create a mixed list
mixed <- list(
  c("R", "Python", "Java"),
  1:5,
  matrix(1:4, nrow = 2)
)
mixed

# Exercise 8: extract the second programming language
mixed[[1]][2]

 [1]  5  7  9 11 13 15 17 19 21 23 25

[1] "2026-01-01" "2026-02-01" "2026-03-01" "2026-04-01" "2026-05-01"
[6] "2026-06-01"

[1] "M" "N" "O" "P" "Q" "R"

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

[1] 20 18 12  9  5  3

[1] 4 2 6 3 1 5

[[1]]
[1] "R"      "Python" "Java"

[[2]]
[1] 1 2 3 4 5

[[3]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[1] "Python"



- `seq()` provides flexible control over start, end, increment and length.
- `times` repeats the whole object; `each` repeats each element.
- `order()` returns positions/indices.
- `sort()` returns the sorted values.
- `mode()` reports the storage mode.
- Lists can hold elements of different object types.
- `[[ ]]` extracts an element from a list; `[ ]` can return a sublist.
- `letters` gives lowercase alphabets and `LETTERS` gives uppercase alphabets.